print("Welcome to Band Name Generator.")
print("Enter the name of the city where you grew up.")
city = input()
print("Enter your pet's name.")
animal = input()
print("Your band name could be "+city+" "+animal+".")